version: '3'
services:
  gq-game-service:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./:/GameService
    ports:
      - "9700:9700"
    environment:
      - DC_DS=116.203.234.111
      - DC_GS_SELF=94.130.183.32
    command: python manage.py runserver 0.0.0.0:9700