name: golfquiz
description: Learn the rules of Golf.

version: 0.0.2-8

environment:
  sdk: ">=2.2.2 <3.0.0"

  # Dependencies:
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  provider: ^4.0.2
  simple_animations: ^1.3.6
  uuid: ^2.0.4
  flare_flutter: ^2.0.1
  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.1+1
  progress_dialog: ^1.2.0

  # Developer dependencies:
dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.1

flutter:
  uses-material-design: true

  # Assets:
  assets:
   - assets/images/
   - assets/icons/highscore.png
   - assets/animations/
