version: '3'
services:
  gq-database-service:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./:/DatabaseService
    ports:
      - "9600:9600"
    command: python manage.py runserver 0.0.0.0:9600