version: '3'
services:
  gq-database-service:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./:/DatabaseService
    ports:
      - "9600:8000"
    command: python manage.py runserver [::]:8000
    
