version: '3'
services:
  gq-auth-service:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./:/AuthService
    ports:
      - "9800:9800"
    environment:
      - DC_GS=94.130.183.32
    command: python manage.py runserver 0.0.0.0:9800